### ISSUE TITLE
仓库里的SYsU-lang/parser/parser.y生成c代码编译不通过

### ISSUE THREAD

**Issue by yhgu2000** [arcsysu/SYsU-lang#58]
```
$ cmake --build .
    [2/3] Building CXX object parser/CMakeFiles/sysu-parser.dir/main.cc.o
    FAILED: parser/CMakeFiles/sysu-parser.dir/main.cc.o
    /usr/bin/clang++  -I/usr/lib/llvm-14/include -O2 -g -DNDEBUG -MD -MT parser/CMakeFiles/sysu-parser.dir/main.cc.o -MF parser/CMakeFiles/sysu-parser.dir/main.cc.o.d -o parser/CMakeFiles/sysu-parser.dir/main.cc.o -c /root/WAS/GYH-SYsU-lang/SYsU-lang/build/parser/main.cc
    /root/WAS/GYH-SYsU-lang/SYsU-lang/parser/parser.y:52:10: error: use of undeclared identifier 'YYEOF'
      return YYEOF;
             ^
    1 error generated.
    ninja: build stopped: subcommand failed.
```

把 `SYsU-lang/parser/parser.y` 里的 yylex 和 main 移到第三节就好了，第一节里只做一个 yylex 的声明

**Comment by Yorkking** [comment]
用下面的命令来构建项目。在 README.md 里面编译运行一节有说明：
```bash
cmake -G Ninja \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_INSTALL_PREFIX=$HOME/sysu \
  -DCMAKE_PREFIX_PATH="$(llvm-config --cmakedir)" \
  -DCPACK_SOURCE_IGNORE_FILES=".git/;tester/third_party/" \
  -B $HOME/sysu/build
```

**Comment by yhgu2000** [comment]
> 用下面的命令来构建项目。在 README.md 里面编译运行一节有说明：
> 
> ```shell
> cmake -G Ninja \
>   -DCMAKE_BUILD_TYPE=RelWithDebInfo \
>   -DCMAKE_C_COMPILER=clang \
>   -DCMAKE_CXX_COMPILER=clang++ \
>   -DCMAKE_INSTALL_PREFIX=$HOME/sysu \
>   -DCMAKE_PREFIX_PATH="$(llvm-config --cmakedir)" \
>   -DCPACK_SOURCE_IGNORE_FILES=".git/;tester/third_party/" \
>   -B $HOME/sysu/build
> ```

不是这个问题，我是说`SYsU-lang/parser/parser.y`编写的问题，里面`#define YYEOF`的生成在`yylex()`后了

**Comment by Yorkking** [comment]
Bison 的手册里面：https://www.gnu.org/software/bison/manual/bison.html#Grammar-File  的 `3.1 Outline of a Bison Grammar` 这一节里面给出了编写 .y 文件的规范，是这样一个形式
```bison
%{
  Prologue
%}

Bison declarations

%%
Grammar rules
%%

Epilogue
```
也是把 Prologue 放到最前面。所以我觉得仓库里的写法是没问题的。

**Comment by Yorkking** [comment]
所以如果你编译不过，我怀疑是bison版本的问题。

**Comment by wu-kan** [comment]
`YYEOF` 定义在生成的 `parser.hh` 里

```cpp
/* A Bison parser, made by GNU Bison 3.7.5.  */

/* Bison interface for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

#ifndef YY_YY_PARSER_HH_INCLUDED
# define YY_YY_PARSER_HH_INCLUDED
/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int yydebug;
#endif

/* Token kinds.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    YYEMPTY = -2,
    YYEOF = 0,                     /* "end of file"  */
    YYerror = 256,                 /* error  */
    YYUNDEF = 257,                 /* "invalid token"  */
    T_NUMERIC_CONSTANT = 258,      /* T_NUMERIC_CONSTANT  */
    T_IDENTIFIER = 259,            /* T_IDENTIFIER  */
    T_INT = 260,                   /* T_INT  */
    T_RETURN = 261,                /* T_RETURN  */
    T_SEMI = 262,                  /* T_SEMI  */
    T_L_PAREN = 263,               /* T_L_PAREN  */
    T_R_PAREN = 264,               /* T_R_PAREN  */
    T_L_BRACE = 265,               /* T_L_BRACE  */
    T_R_BRACE = 266                /* T_R_BRACE  */
  };
  typedef enum yytokentype yytoken_kind_t;
#endif

/* Value type.  */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef int YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif


extern YYSTYPE yylval;

int yyparse (void);

#endif /* !YY_YY_PARSER_HH_INCLUDED  */

```

而 `parser.y` 的开头就是

```cpp
#include "parser.hh"
```

所以按道理来说不该出现这个问题，从你的 log 来看可能是 cmake 的目录没设置对，导致编译的时候没把这个头文件 include 进来，建议 rm 掉原来的文件重新按照 README 操作一遍。

**Comment by yhgu2000** [comment]
> `YYEOF` 定义在生成的 `parser.hh` 里
> 
> ```c++
> /* A Bison parser, made by GNU Bison 3.7.5.  */
> 
> /* Bison interface for Yacc-like parsers in C
> 
>    Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
>    Inc.
> 
>    This program is free software: you can redistribute it and/or modify
>    it under the terms of the GNU General Public License as published by
>    the Free Software Foundation, either version 3 of the License, or
>    (at your option) any later version.
> 
>    This program is distributed in the hope that it will be useful,
>    but WITHOUT ANY WARRANTY; without even the implied warranty of
>    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>    GNU General Public License for more details.
> 
>    You should have received a copy of the GNU General Public License
>    along with this program.  If not, see <http://www.gnu.org/licenses/>.  */
> 
> /* As a special exception, you may create a larger work that contains
>    part or all of the Bison parser skeleton and distribute that work
>    under terms of your choice, so long as that work isn't itself a
>    parser generator using the skeleton or a modified version thereof
>    as a parser skeleton.  Alternatively, if you modify or redistribute
>    the parser skeleton itself, you may (at your option) remove this
>    special exception, which will cause the skeleton and the resulting
>    Bison output files to be licensed under the GNU General Public
>    License without this special exception.
> 
>    This special exception was added by the Free Software Foundation in
>    version 2.2 of Bison.  */
> 
> /* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
>    especially those whose name start with YY_ or yy_.  They are
>    private implementation details that can be changed or removed.  */
> 
> #ifndef YY_YY_PARSER_HH_INCLUDED
> # define YY_YY_PARSER_HH_INCLUDED
> /* Debug traces.  */
> #ifndef YYDEBUG
> # define YYDEBUG 0
> #endif
> #if YYDEBUG
> extern int yydebug;
> #endif
> 
> /* Token kinds.  */
> #ifndef YYTOKENTYPE
> # define YYTOKENTYPE
>   enum yytokentype
>   {
>     YYEMPTY = -2,
>     YYEOF = 0,                     /* "end of file"  */
>     YYerror = 256,                 /* error  */
>     YYUNDEF = 257,                 /* "invalid token"  */
>     T_NUMERIC_CONSTANT = 258,      /* T_NUMERIC_CONSTANT  */
>     T_IDENTIFIER = 259,            /* T_IDENTIFIER  */
>     T_INT = 260,                   /* T_INT  */
>     T_RETURN = 261,                /* T_RETURN  */
>     T_SEMI = 262,                  /* T_SEMI  */
>     T_L_PAREN = 263,               /* T_L_PAREN  */
>     T_R_PAREN = 264,               /* T_R_PAREN  */
>     T_L_BRACE = 265,               /* T_L_BRACE  */
>     T_R_BRACE = 266                /* T_R_BRACE  */
>   };
>   typedef enum yytokentype yytoken_kind_t;
> #endif
> 
> /* Value type.  */
> #if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
> typedef int YYSTYPE;
> # define YYSTYPE_IS_TRIVIAL 1
> # define YYSTYPE_IS_DECLARED 1
> #endif
> 
> 
> extern YYSTYPE yylval;
> 
> int yyparse (void);
> 
> #endif /* !YY_YY_PARSER_HH_INCLUDED  */
> ```
> 
> 而 `parser.y` 的开头就是
> 
> ```c++
> #include "parser.hh"
> ```
> 
> 所以按道理来说不该出现这个问题，从你的 log 来看可能是 cmake 的目录没设置对，导致编译的时候没把这个头文件 include 进来，建议 rm 掉原来的文件重新按照 README 操作一遍。

我这边生成的`parser.hh`里没有定义YYEOF：

```c
/* A Bison parser, made by GNU Bison 3.5.1.  */

/* Bison interface for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2020 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* Undocumented macros, especially those whose name start with YY_,
   are private implementation details.  Do not rely on them.  */

#ifndef YY_YY_PARSER_HH_INCLUDED
# define YY_YY_PARSER_HH_INCLUDED
/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int yydebug;
#endif

/* Token type.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    T_NUMERIC_CONSTANT = 258,
    T_IDENTIFIER = 259,
    T_INT = 260,
    T_RETURN = 261,
    T_SEMI = 262,
    T_L_PAREN = 263,
    T_R_PAREN = 264,
    T_L_BRACE = 265,
    T_R_BRACE = 266
  };
#endif

/* Value type.  */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef int YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif


extern YYSTYPE yylval;

int yyparse (void);

#endif /* !YY_YY_PARSER_HH_INCLUDED  */
```

我用的是 Flex 2.6.4，Bison 3.5.1，Clang 14.0.6，CMake 3.25.1

这里是整个生成的 `$HOME/sysu`：[sysu.tar.gz](https://github.com/arcsysu/SYsU-lang/files/10398151/sysu.tar.gz)

**Comment by yhgu2000** [comment]
看来应该是Bison版本的问题

**Comment by yhgu2000** [comment]
> Bison 的手册里面：https://www.gnu.org/software/bison/manual/bison.html#Grammar-File 的 `3.1 Outline of a Bison Grammar` 这一节里面给出了编写 .y 文件的规范，是这样一个形式
> 
> ```yacc
> %{
>   Prologue
> %}
> 
> Bison declarations
> 
> %%
> Grammar rules
> %%
> 
> Epilogue
> ```
> 
> 也是把 Prologue 放到最前面。所以我觉得仓库里的写法是没问题的。

我今天去仔细读了一下Bison文档：https://www.gnu.org/software/bison/manual/html_node/Grammar-Layout.html

> The epilogue can contain any code you want to use. Often the definitions of functions declared in the prologue go here. In a simple program, all the rest of the program can go here.

**Comment by wu-kan** [comment]
> > Bison 的手册里面：https://www.gnu.org/software/bison/manual/bison.html#Grammar-File 的 `3.1 Outline of a Bison Grammar` 这一节里面给出了编写 .y 文件的规范，是这样一个形式
> > ```yacc
> > %{
> >   Prologue
> > %}
> > 
> > Bison declarations
> > 
> > %%
> > Grammar rules
> > %%
> > 
> > Epilogue
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 也是把 Prologue 放到最前面。所以我觉得仓库里的写法是没问题的。
> 
> 我今天去仔细读了一下Bison文档：https://www.gnu.org/software/bison/manual/html_node/Grammar-Layout.html
> 
> > The epilogue can contain any code you want to use. Often the definitions of functions declared in the prologue go here. In a simple program, all the rest of the program can go here.

可以写Epilogue也可以写Prologue，但是我是考虑到可能会有把parser和lexer链在一起的情况，对我们来说定义放在一个统一的头文件里面会比较好。
