### ISSUE TITLE
给 lexer/README.md 添加一些词法定义会不会更好

### ISSUE THREAD

**Issue by yhgu2000** [arcsysu/SYsU-lang#59]
给个SysY语言词法定义文档链接或者 clang -dump-tokens 的文档链接？

**Comment by Yorkking** [comment]
可以做也可以不做，留给学生自行探索也行，但实际上在 [Discussioins](https://github.com/arcsysu/SYsU-lang/discussions/10)  里面有同学已经给了。

**Comment by yhgu2000** [comment]
OK
