### ISSUE TITLE
实验一词法分析中，大于符号和小于符号的解析。

### ISSUE THREAD

**Issue by zwshan** [arcsysu/SYsU-lang#67]
在实验一词法分析中，刚开始我在编写大于符号和小于符号的代码的时候，没有加上转移斜杠\，所以直接在build阶段了。然后我在chatgpt中询问了“使用flex进行C语言词法分析的时候，大于号和小于号的代码应该怎么写？”这个问题，AI提示我需要添加上转义符号，然后我添加上转义符号后build就通过了。
但是似乎评测器对我的>和<符号的代码编写还是不太满意，请问一下这个报错信息是什么意思呢？我的代码是错在哪里了呢？
<img width="658" alt="image" src="https://user-images.githubusercontent.com/62176674/220849030-ffbd2181-310e-47a7-967d-96369408c5e0.png">
<img width="817" alt="image" src="https://user-images.githubusercontent.com/62176674/220849097-e9f4fc27-b4c0-477e-bdaf-9a30eb810e7d.png">

**Comment by yhgu2000** [comment]
你这个问题好像和大于号小于号没关系吧，好像是你没识别出逗号`,`这个词法单元

**Comment by zwshan** [comment]
那为啥comma前面有一个大于号呢，unknown前面与一个小于号，我以为是大于号和小于号没有识别出来。
那我去试试，感谢助教。/doge

**Comment by Yorkking** [comment]
那个 `<` 和 `>` 是评测脚本的前导输出来着，`< xxxx` 表示理应输出 xxxx , 而 `> yyyy` 表示实际输出 yyyy
不过看起来可以修改为更加好理解的符号？ @wu-kan

**Comment by zwshan** [comment]
感谢两位助教哥哥，我发现我的问题了，确实是逗号没有解析出来。

我现在发现不同的符号解析的代码的顺序是会影响最终的输出结果的。

另外后续我会把问题提交到discussion模版的，我刚刚来知道issue是应该提交对实验的建议。
